version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd ./angular-project && pwd && npm install -g @angular/cli@9.0.6 && ng version

  pre_build:
    commands:
      - pwd
      - ls -R
      - npm install
      - ng version

  build:
    commands:
      - ng build

artifacts:
  base-directory: "dist/my-angular-project"
  files:
    - "**/*"
