version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@9.0.6

  pre_build:
    commands:
      - cd angular-project495/angular-project
      - npm install

  build:
    commands:
      - cd angular-project495/angular-project
      - ng build --prod

artifacts:
  base-directory: "angular-project495/angular-project/dist/my-angular-project"
  files:
    - "**/*"
