version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        cd angular-project
      - npm install -g @angular/cli@9.0.6

  pre_build:
    commands:
      - npm install
       - pwd
       - ls -R

  build:
    commands:
      - ng build 

artifacts:
  base-directory: "dist/my-angular-project"
  files:
    - "**/*"
