# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 12
#     commands:
#       - npm install -g @angular/cli@9.0.6

#   pre_build:
#     commands:
#       - cd angular-project
#       - npm install

#   build:
#     commands:
#       - ng build 

#   post_build:
#     commands:
#       - aws s3 cp dist/my-angular-project s3://deploymentbucket495 --recursive

# artifacts:
#   base-directory: "dist/my-angular-project"
#   files:
#     - "**/*"

# artifacts:
#   files:
#     - angular-project/dist/my-angular-project/**/*
#     - angular-project/appspec.yml
#     - hooks/**/*


version: 0.2

env:
  variables:
    DOCKERHUB_TOKEN: "dckr_pat_8iDau_K7OySmi2AC98bP7wK_qek"
    DOCKERHUB_USER: "Ramu455"

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin

  build:
    commands:
      - docker build -t my-angular-app:latest .

  post_build:
    commands:
      - docker tag my-angular-app:latest ${DOCKERHUB_USER}/angular-docker-repo-bill:latest
      - docker push ${DOCKERHUB_USER}/angular-docker-repo-bill:latest























