# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 12
#     commands:
#       - npm install -g @angular/cli@9.0.6

#   pre_build:
#     commands:
#       - cd angular-project
#       - npm install

#   build:
#     commands:
#       - ng build 

#   post_build:
#     commands:
#       - aws s3 cp dist/my-angular-project s3://deploymentbucket495 --recursive

# artifacts:
#   base-directory: "dist/my-angular-project"
#   files:
#     - "**/*"

# artifacts:
#   files:
#     - angular-project/dist/my-angular-project/**/*
#     - angular-project/appspec.yml
#     - hooks/**/*


version: 0.2

env:
  parameter-store:
    DOCKERHUB_USER: "/docker/username"   
  secrets-manager:
    DOCKERHUB_TOKEN: "credentials:token"

phases:
  pre_build:
    commands:
      - echo "===== DEBUG: Checking env variables ====="
      - echo "DOCKERHUB_USER=${DOCKERHUB_USER}"
      - echo "DOCKERHUB_TOKEN length=${#DOCKERHUB_TOKEN}"
      - echo -n ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - echo "===== Docker login completed ====="

  build:
    commands:
      - echo "===== Build phase started ====="
      - docker build -t my-angular-app:latest .
      - echo "===== Build phase completed ====="

  post_build:
    commands:
      - echo "===== Post-build phase started ====="
      - docker tag my-angular-app:latest ${DOCKERHUB_USER}/angular-docker-repo-bill:latest
      - docker push ${DOCKERHUB_USER}/angular-docker-repo-bill:latest
      - echo "===== Post-build completed ====="













