version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@9.0.6

  pre_build:
    commands:
      - cd ./angular-project
      - npm install
      

  build:
    commands:
      - ng build

artifacts:
    commands:
      - aws s3 cp dist/my-angular-project/ s3://deploymentbucket495 --recursive
