# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 12
#     commands:
#       - npm install -g @angular/cli@9.0.6

#   pre_build:
#     commands:
#       - cd angular-project
#       - npm install

#   build:
#     commands:
#       - ng build

#   post_build:
#     commands:
#       - aws s3 cp dist/my-angular-project s3://deploymentbucket495 --recursive

# artifacts:
#   base-directory: "dist/my-angular-project"
#   files:
#     - "**/*"

# artifacts:
#   files:
#     - angular-project/dist/my-angular-project/**/*
#     - angular-project/appspec.yml
#     - hooks/**/*

version: 0.2

env:
  parameter-store:
    DOCKERHUB_USER: "/docker/username"
  secrets-manager:
    DOCKERHUB_TOKEN: "credentials:token"

phases:
  pre_build:
    commands:
      - echo -n ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin

  build:
    commands:
      - cd angular-project
      - docker build -t my-angular-app:${CODEBUILD_BUILD_NUMBER} .

  post_build:
    commands:
      - docker tag my-angular-app:${CODEBUILD_BUILD_NUMBER} ${DOCKERHUB_USER}/angular-docker-repo-bill:${CODEBUILD_BUILD_NUMBER}
      - docker push ${DOCKERHUB_USER}/angular-docker-repo-bill:${CODEBUILD_BUILD_NUMBER}
      - printf '[{"name":"angular","imageUri":"%s"}]' docker.io/ramu455/angular-docker-repo-bill:${CODEBUILD_BUILD_NUMBER} > UpdatedTaskDefinition.json

artifacts:
  files:
    - UpdatedTaskDefinition.json
